; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ESP32-S3-N16R8: 16MB Flash + 8MB OPI PSRAM
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

lib_deps = adafruit/Adafruit NeoPixel@^1.12.0

; 墨水屏 SPI 默认引脚 + 板载 WS2812 RGB LED + 外接按键
build_flags =
    -DBOARD_HAS_PSRAM
    -DPIN_RGB_LED=48
    -DPIN_EPD_BUSY=14
    -DPIN_EPD_RST=13
    -DPIN_EPD_DC=12
    -DPIN_EPD_CS=11
    -DPIN_EPD_SCLK=10
    -DPIN_EPD_DIN=9
    -DPIN_BTN_MODE=4
    -DPIN_BTN_ACTION=5
    -DPIN_BTN_SYSTEM=6
